project_id = "klkrzfwvrmffqkmkyqrh"

[functions.connected-accounts]
verify_jwt = false

[functions.toggle-page-automation]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.dashboard-stats]
verify_jwt = false

[functions.execution-logs]
verify_jwt = false

[functions.me]
verify_jwt = false

[functions.automations]
verify_jwt = false

[functions.page-memory]
verify_jwt = false